import React, { useState } from "react";

const FeedbackForm = () => {
  const [feedback, setFeedback] = useState("");

  const handleInputChange = (e) => {
    const { value } = e.target;
    setFeedback(value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log("Feedback submitted:", feedback);
  };

  return (
    <div className="max-w-md mx-auto mt-10 p-6 bg-[#2E3496] rounded-md shadow-md">
      <h2 className="text-2xl font-semibold mb-4 text-white">Feedback Form</h2>
      <p className="text-gray-300 mb-4">
        Feedback on the tasks generated by AI. AI depends on your feedback to
        generate the set of tasks for the upcoming week.
      </p>
      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label
            className="block text-gray-300 text-sm font-bold mb-2"
            htmlFor="feedback"
          >
            Your Feedback:
          </label>
          <textarea
            id="feedback"
            name="feedback"
            value={feedback}
            onChange={handleInputChange}
            rows="4"
            className="w-full px-4 py-2 border rounded-md focus:outline-none focus:border-blue-500 bg-gray-700 text-white"
            placeholder="Provide your feedback here."
            required
          ></textarea>
        </div>

        <button
          type="submit"
          className="w-full bg-blue-500 text-white py-2 rounded-md hover:bg-blue-600"
        >
          Submit Feedback
        </button>
      </form>
    </div>
  );
};

export default FeedbackForm;
